package Animacion;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import AppPackage.AnimationClass;
import Frames.Login;
import Frames.Login2;
import Frames.Plataforma;
import Frames.Plataforma;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
/**
 *
 * @author Langas
 */
public class Animacion extends javax.swing.JFrame {

    /**
     * Creates new form Animacion
     */
    public Animacion() {
        initComponents();
        this.setSize(1247, 790);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2 - this.getSize().width/2,dim.height/2-this.getSize().height/2);
        
        AnimationClass ani = new AnimationClass();
        
        //Movimiento Rojo a la Izquierda
        ani.jLabelXLeft(Rosa.getX(), -1000, 2, 1, Rosa);
        
        //Movimiento Amarillo derecha
        ani.jLabelXRight(Amarillo.getX(),1200, 4, 1,Amarillo);
        
        //Movimiento Verde abajo
        ani.jLabelYDown(Verde.getY(), 1000, 4, 1, Verde);
        
        //Movimiento Azul Abajo
        ani.jLabelYDown(Azul.getY(),1000, 2, 1, Azul);
        
        //Texto Movimiento
        ani.jLabelXRight(-500, 0, 2, 1, txt_Titulo);
        
    
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_Titulo = new javax.swing.JLabel();
        Azul = new javax.swing.JLabel();
        Rosa = new javax.swing.JLabel();
        Amarillo = new javax.swing.JLabel();
        Verde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Titulo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 30)); // NOI18N
        txt_Titulo.setForeground(new java.awt.Color(102, 102, 102));
        txt_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Animacion_Bienvenida/Logo4.png"))); // NOI18N
        txt_Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_TituloMouseClicked(evt);
            }
        });
        jPanel1.add(txt_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-500, 270, 1280, 250));

        Azul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Azul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Animacion_Bienvenida/Trazado 7.png"))); // NOI18N
        Azul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AzulMouseClicked(evt);
            }
        });
        jPanel1.add(Azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 970, 690));

        Rosa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Rosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Animacion_Bienvenida/Trazado 4.png"))); // NOI18N
        Rosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RosaMouseClicked(evt);
            }
        });
        jPanel1.add(Rosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -20, 1010, 610));

        Amarillo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Amarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Animacion_Bienvenida/Trazado 5.png"))); // NOI18N
        Amarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AmarilloMouseClicked(evt);
            }
        });
        jPanel1.add(Amarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 840, 620));

        Verde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Verde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Animacion_Bienvenida/Trazado 6.png"))); // NOI18N
        Verde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerdeMouseClicked(evt);
            }
        });
        jPanel1.add(Verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 375, 710, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1247, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_TituloMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Plataforma plata = new Plataforma();
        plata.setVisible(true);
    }//GEN-LAST:event_txt_TituloMouseClicked

    private void AzulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AzulMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Plataforma plata = new Plataforma();
        plata.setVisible(true);
    }//GEN-LAST:event_AzulMouseClicked

    private void RosaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RosaMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Plataforma plata = new Plataforma();
        plata.setVisible(true);
    }//GEN-LAST:event_RosaMouseClicked

    private void AmarilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AmarilloMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Plataforma plata = new Plataforma();
        plata.setVisible(true);
    }//GEN-LAST:event_AmarilloMouseClicked

    private void VerdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerdeMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Plataforma plata = new Plataforma();
        plata.setVisible(true);
    }//GEN-LAST:event_VerdeMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Plataforma plata = new Plataforma();
        plata.setVisible(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Animacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Animacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Animacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Animacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Animacion().setVisible(true);
                

                 
                 //new Animacion().dispose();
                 //System.exit(0);
                 //Login2 login = new Login2();
                 //login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amarillo;
    private javax.swing.JLabel Azul;
    private javax.swing.JLabel Rosa;
    private javax.swing.JLabel Verde;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_Titulo;
    // End of variables declaration//GEN-END:variables
}
